# MULTIPLE RESOLUTIONS TRAINING
[general]
caption_extension = ".txt"
batch_size = 1
enable_bucket = true # Preserve Aspect Ratio of Original Image
bucket_no_upscale = true # Do not Upscale videos and images if they are below the target resolution. This is found to introduce compression artifacts
num_repeats = 1 # optional, default is 1. Number of times to repeat the dataset. Useful to balance the multiple datasets with different sizes.

# other datasets can be added here. each dataset can have different configurations

# Image Training Settings

# 320x320
[[datasets]]
resolution = [320 , 320] # Train Images at 0.10 MP resolution - fastest image bucket
image_directory = "/workspace/musubi-tuner/dataset"
cache_directory = "/workspace/musubi-tuner/dataset/cache/img/320"

# 480x480
[[datasets]]
resolution = [480 , 480] # Train Images at 0.23 MP resolution - balances speed and quality
image_directory = "/workspace/musubi-tuner/dataset"
cache_directory = "/workspace/musubi-tuner/dataset/cache/img/480"

# 640x640
[[datasets]]
resolution = [640 , 640] # Train Images at 0.41 MP resolution - solid comprimise between visual quality and performance
image_directory = "/workspace/musubi-tuner/dataset"
cache_directory = "/workspace/musubi-tuner/dataset/cache/img/640"

# 960x960
[[datasets]]
resolution = [960 , 960] # Train Images at 0.92 MP resolution - preserves finer details
image_directory = "/workspace/musubi-tuner/dataset"
cache_directory = "/workspace/musubi-tuner/dataset/cache/img/960"

# Video Training Settings

# 128x128
[[datasets]]
resolution = [128,128] # 0.016 MP. Fastest/lowest detail video bucket
video_directory = "/workspace/musubi-tuner/dataset"
cache_directory = "/workspace/musubi-tuner/dataset/cache/video/128"
frame_extraction = "full"
max_frames = 81 # Start at beginning of video and take 5 seconds at 16 FPS

# 256x256
[[datasets]]
resolution = [256,256] # 0.066 MP. Mid-quality video bucket
video_directory = "/workspace/musubi-tuner/dataset"
cache_directory = "/workspace/musubi-tuner/dataset/cache/video/256"
frame_extraction = "full"
num_repeats = 2
max_frames = 81 # Start at beginning of video and take 5 seconds at 16 FPS

# 320x320
[[datasets]]
resolution = [320,320] # 0.102 MP. Highest-quality video bucket in this preset
video_directory = "/workspace/musubi-tuner/dataset"
cache_directory = "/workspace/musubi-tuner/dataset/cache/video/320"
frame_extraction = "full"
max_frames = 81 # Start at beginning of video and take 5 seconds at 16 FPS