# turbo.toml
# Lower VRAM / Faster Training at the cost of fine detail preservation
[general]
caption_extension = ".txt"
batch_size = 1
enable_bucket = true # preserving aspect ratio.
bucket_no_upscale = true # Do not Upscale videos and images if they are below the target resolution. This is found to introduce compression artifacts
num_repeats = 1

[[datasets]]
resolution = [480, 480] 
image_directory = "/workspace/musubi-tuner/dataset" # If you change this, the upload feature in the webui won't work
cache_directory = "/workspace/musubi-tuner/dataset/cache"

[[datasets]]
video_directory = "/workspace/musubi-tuner/dataset"
cache_directory = "/workspace/musubi-tuner/dataset/videocache"
frame_extraction = "full" #start from the beginning of the video
max_frames = 81 #only take 5 seconds
resolution = [208,208] # 0.048 MP For Videos. Will be fast with possible quality degredation
